
module.exports = {
    tags: ['rules'],
    cmd: ['peraturan', 'rules'],
    help: ['rules'],
    exec: (m) => {
        m.reply('*_PERATURAN REALM_*\n-BERAKAL SEHAT\n-DILARANG NGE CHEAT KECUALI ADMIN (DALAM BENTUK APAPUN)\n-DILARANG MENGGANDAKAN BARANG DALAM BENTUK APAPUN\n-MELIHAT CHEATER APALAGI YANG BERBAHAYA LANGSUNG LAPOR ADMIN, SENJATA DEWA CUMA DIPEGANG ADMIN\n-DILARANG NGAMBIL TANPA IZIN (KALO DAPET IZIN DARI PEMILIK YA GAPAPA)\n-RUSUH AUTO SIKSA\n-DILARANG MENYERANG TEMAN SENDIRI\n-USAHAKAN INTRO DI GRUP BUAT NEW MEM\n-PENGEN LINK REALM MINTA KE wa.me/6285360065102')
    }
}
